/**
 * ===============================
 * SOURCE MAPS IN REACT
 * ===============================
 *
 * 🔹 What are Source Maps?
 *
 * Source maps are files that create a connection
 * between the original source code (JSX / ES6 / TS)
 * and the transformed code (compiled / bundled JavaScript).
 *
 *
 * 🔹 Why do we need Source Maps?
 *
 * - React code is usually written in:
 *   • JSX
 *   • Modern JavaScript (ES6+)
 *   • TypeScript
 *
 * - Browsers cannot understand these directly
 * - Tools like Babel & Bundlers convert them into
 *   plain JavaScript
 *
 * - After conversion:
 *   • Variable names change
 *   • Line numbers change
 *   • Code becomes hard to read
 *
 * 👉 Without source maps, debugging becomes very difficult
 *
 *
 * 🔹 What are Source Maps used for?
 *
 * - To debug original source code in browser DevTools
 * - To show original file names instead of bundled files
 * - To point errors to correct line numbers in JSX files
 * - To set breakpoints in original React components
 *
 *
 * 🔹 How Source Maps work (Flow)
 *
 * Original Code (JSX / ES6)
 *        ↓
 * Babel / Bundler
 *        ↓
 * Compiled JavaScript + Source Map (.map file)
 *        ↓
 * Browser DevTools
 *        ↓
 * Original source code shown while debugging
 *
 *
 * 🔹 Example (Without Source Maps)
 *
 * Error shown in browser:
 *   main.js:1:2356
 *
 * ❌ Difficult to understand
 * ❌ No clue which React component failed
 *
 *
 * 🔹 Example (With Source Maps)
 *
 * Error shown in browser:
 *   App.jsx:12
 *
 * ✅ Clear error location
 * ✅ Easy debugging
 *
 *
 * 🔹 Common Source Map File
 *
 * - main.js.map
 * - bundle.js.map
 *
 * These files map compiled code back to original source
 *
 *
 * 🔹 Source Maps in React (Development vs Production)
 *
 * Development:
 * - Source maps are ENABLED
 * - Easy debugging
 *
 * Production:
 * - Source maps may be:
 *   • Disabled (security)
 *   • Uploaded to error tracking tools (Sentry)
 *
 *
 * 🔹 Tools that generate Source Maps
 *
 * - Babel
 * - Webpack
 * - Vite
 * - CRA (Create React App)
 *
 *
 * 🔑 One-line Revision
 *
 * Source maps allow developers to debug original React source code
 * even though the browser runs compiled JavaScript.
 */







/**
 * =====================================
 * WAYS TO GENERATE SOURCE MAPS
 * =====================================
 *
 * Source maps are generated during the build / transpilation process
 * using tools that transform modern code (JSX, ES6+, TS)
 * into browser-compatible JavaScript.
 *
 *
 * 🔹 1️⃣ Using Babel (CLI or Bundler)
 *
 * - Babel can generate source maps while transpiling code
 * - Source maps link JSX / ES6 code to compiled JavaScript
 *
 * Example (Babel CLI):
 *   npx babel src --out-dir dist --source-maps
 *
 * Output:
 * - dist/index.js
 * - dist/index.js.map
 *
 *
 * 🔹 2️⃣ Using Webpack
 *
 * - Webpack has built-in support for source maps
 * - Controlled using the `devtool` option
 *
 * Common devtool values:
 * - "source-map"        → full source map (production)
 * - "inline-source-map" → embedded inside JS file (development)
 * - "eval-source-map"   → fastest rebuilds (dev only)
 *
 *
 * 🔹 3️⃣ Using Vite
 *
 * - Vite automatically enables source maps in development
 * - Uses ES modules + native browser support
 *
 * Production:
 * - Source maps can be enabled or disabled manually
 *
 *
 * 🔹 4️⃣ Using Create React App (CRA)
 *
 * - Source maps enabled by default in development
 * - Production source maps are generated automatically
 * - Can be disabled using environment variables
 *
 *
 * 🔹 5️⃣ Using TypeScript Compiler
 *
 * - TypeScript can generate source maps
 *
 * Example:
 *   tsc --sourceMap
 *
 * Output:
 * - index.js
 * - index.js.map
 *
 *
 * 🔹 6️⃣ Inline Source Maps
 *
 * - Source map is embedded directly into the JS file
 * - No separate .map file is created
 *
 * Used mostly for:
 * - Development
 * - Debugging
 *
 *
 * 🔹 7️⃣ External Source Maps
 *
 * - Source map is generated as a separate `.map` file
 * - Referenced using sourceMappingURL
 *
 * Used mostly for:
 * - Production builds
 * - Error tracking tools (Sentry, Bugsnag)
 *
 *
 * 🔑 One-line Revision
 *
 * Source maps are generated by transpilers and bundlers like
 * Babel, Webpack, Vite, CRA, and TypeScript to map compiled
 * code back to original source for debugging.
 */
